name: fragrance-infer-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-inference-server-http
      - azure-storage-blob
      - scikit-learn
      - joblib
      - numpy
      - pandas
